#!/bin/sh

#for amazon linux 2
sudo yum update -y
sudo yum install docker-engine -y

#Add group membership for the default ec2-user so you can run all docker commands without using the sudo command:
sudo usermod -a -G docker ec2-user
id ec2-user
# Reload a Linux user's group assignments to docker w/o logout
newgrp docker

#docker compose
sudo yum install python3-pip
# 2. Then run any one of the following
sudo pip3 install docker-compose # with root access

#enable docker service at boot
sudo systemctl enable docker.service
sudo systemctl start docker.service

#install git
sudo yum install git -y

#install java
sudo amazon-linux-extras install java-openjdk11

#pull repo
git clone https://github.com/Nuvalence/sample-spring-postgres-app.git




#convert docker compose to k8s files

#download kompose
curl -L https://github.com/kubernetes/kompose/releases/download/v1.26.0/kompose-linux-amd64 -o kompose
chmod +x kompose
sudo mv ./kompose /usr/local/bin/kompose


#go to folder with docker compsoe file and run this to get the k8s files outputed
kompose convert

